version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    labels:
      - "Technical Debt"
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: weekly
    labels:
      - "Technical Debt"
