server:
  port: 8081

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://retail-ddd-example.eu.auth0.com/
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect