logging:
  pattern:
    console:

spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        name: nerd-alert-shop
        stdio: true
        instructions: "This shop offers a wide range of tech-products one can search for and order"
