apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop-frontend.fullname" . }}
  labels:
    {{- include "shop-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shop-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/app-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "shop-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: app-config
              mountPath: /usr/share/nginx/html/app.env
              subPath: app.env
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: {{ include "shop-frontend.fullname" . }}-config
