{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "shop-frontend.fullname" . }}
  labels:
    {{- include "shop-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.ingress.hosts }}
      {{- $host := .host }}
      {{- range .paths }}
    - kind: Rule
      match: Host(`{{ $host }}`) && PathPrefix(`{{ .path }}`)
      services:
        - name: {{ include "shop-frontend.fullname" $ }}
          port: {{ $.Values.service.port }}
      {{- end }}
    {{- end }}
{{- end }}
