image:
  pullPolicy: Never

ingress:
  enabled: true
  stripPrefix:
    enabled: false
    prefixes: []
  hosts:
    - host: localhost
      paths:
        - path: /api
          pathType: Prefix

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "local"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-rw:5432/test"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: password
  - name: SERVER_PORT
    value: "8080"
