image:
  pullPolicy: Never

ingress:
  enabled: true
  stripPrefix:
    enabled: false
    prefixes: []
  hosts:
    - host: localhost
      paths:
        - path: /api
          pathType: Prefix

env:
  - name: SWAGGER_API_ENABLED
    value: "false"
  - name: ISSUER_URI
    value: "https://retail-ddd-example.eu.auth0.com/"
  - name: DATABASE_URL
    value: "jdbc:postgresql://postgres-rw:5432/test"
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: username
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth
        key: password
