image:
  pullPolicy: Never

ingress:
  enabled: true
  stripPrefix:
    enabled: false
    prefixes: []
  hosts:
    - host: localhost
      paths:
        - path: /api
          pathType: Prefix

application:
  database:
    type: postgres
    url: "jdbc:postgresql://postgres-rw:5432/test"
    user: "test"
    password: "test"
  open-api-specs:
    enabled: false
  sample-data:
    enabled: true
  security:
    issuer-uri: "https://retail-ddd-example.eu.auth0.com/"
