image:
  pullPolicy: Never

ingress:
  enabled: true
  stripPrefix:
    enabled: true
    prefixes:
      - /delivery
  hosts:
    - host: localhost
      paths:
        - path: /delivery
          pathType: Prefix

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "local"
  - name: SERVER_PORT
    value: "8080"
