image:
  pullPolicy: Never

ingress:
  enabled: true
  stripPrefix:
    enabled: true
    prefixes:
      - /delivery
  hosts:
    - host: localhost
      paths:
        - path: /delivery
          pathType: Prefix

env:
  - name: SWAGGER_API_ENABLED
    value: "false"
