
# Local development values for shop-frontend
# Override production values for local development

image:
  tag: "local"

service:
  type: LoadBalancer

ingress:
  enabled: true
  hosts:
    - host: shop-frontend.local
      paths:
        - path: /
          pathType: ImplementationSpecific
