image:
  pullPolicy: Never

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

env:
  SHOP_BACKEND_URL: "http://localhost:8080"
  OAUTH_DOMAIN: "retail-ddd-example.eu.auth0.com"
  OAUTH_CLIENT_ID: "22pHgiuTCCLFKHK7SMbWkCzohwar8knS"
  OAUTH_AUDIENCE: ""
