# Local development values for warehouse-backend
# Override production values for local development

image:
  tag: "local"

service:
  type: LoadBalancer

ingress:
  enabled: true
  hosts:
    - host: warehouse-backend.local
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "local"
  - name: SERVER_PORT
    value: "8080"