server:
  port: ${PORT:8080}

shop:
  backend:
    url: ${SHOP_BACKEND_URL:http://localhost:8081}

logging:
  pattern:
    console: "%nopex"
  level:
    root: OFF

spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        name: nerd-alert-shop
        stdio: true
        instructions: "This shop offers a wide range of tech-products one can search for and order"
